openapi: 3.0.3
info:
  title: Users microservice - OpenAPI 3.0
  description: Users microservice API Spec
  version: 1.0.0

servers:
  - url: api/v1

paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      description: Get all users information
      operationId: getUsers
      parameters:
        - in: query
          name: userIds
          description: List of user ids to fetch
          required: false
          schema:
            type: array
            default: [ ]
            items:
              type: string
              format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../shared-components/shared-spec.yaml#/components/schemas/ApiUser'
        '400':
          description: Invalid request
    post:
      tags:
        - Users
      summary: Create user
      description: Create a user with respect to keycload userId
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../shared-components/shared-spec.yaml#/components/schemas/ApiUser'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../shared-components/shared-spec.yaml#/components/schemas/ApiUser'
        '400':
          description: Invalid request
    put:
      tags:
        - Users
      summary: Update user
      description: Udpdate user address only in database and not in keycloak
      operationId: updateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../shared-components/shared-spec.yaml#/components/schemas/ApiUser'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../shared-components/shared-spec.yaml#/components/schemas/ApiUser'
        '400':
          description: Invalid request