openapi: 3.0.3
info:
  title: Users microservice - OpenAPI 3.0
  description: Users microservice API Spec
  version: 1.0.0

servers:
  - url: api/v1

paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      description: Get all users information
      operationId: getUsers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid request

components:
  schemas:
    ApiPayments:
      type: object
      properties:
        id:
          type: string
