openapi: 3.0.3
info:
  title: Accounts microservice - OpenAPI 3.0
  description: Accounts microservice API Spec
  version: 1.0.0

servers:
  - url: api/v1

paths:
  /accounts:
    get:
      tags:
        - Accounts
      summary: Get all accounts
      description: Get all accounts information
      operationId: getAccounts
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../shared-components/shared-spec.yaml#/components/schemas/ApiAccount'
        '400':
          description: Invalid request
    post:
      tags:
        - Accounts
      summary: Create an account for current logged in user
      description: Create an account for current logged in user
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../shared-components/shared-spec.yaml#/components/schemas/ApiAccount'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../shared-components/shared-spec.yaml#/components/schemas/ApiAccount'
        '400':
          description: Invalid request
