openapi: 3.0.3
info:
  title: Accounts microservice - OpenAPI 3.0
  description: Accounts microservice API Spec
  version: 1.0.0

servers:
  - url: api/v1

paths:
  /accounts:
    get:
      tags:
        - Accounts
      summary: Get all accounts
      description: Get all accounts information
      operationId: getAccounts
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid request

components:
  schemas:
    ApiAccounts:
      type: object
      properties:
        id:
          type: string
        accountNumber:
          type: string
        accountName:
          type: string
