services:
  network-deploy-service:
    networks:
      - finobank

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: postgres:16
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres