version: '3.7'

services:
  accountsdb:
    container_name: accountsdb
    ports:
      - "5432:5432"
    volumes:
      - accountsdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  paymentsdb:
    container_name: paymentsdb
    ports:
      - "5433:5432"
    volumes:
      - paymentsdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paymentsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  usersdb:
    container_name: usersdb
    ports:
      - "5434:5432"
    volumes:
      - usersdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: usersdb
    extends:
      file: common-config.yml
      service: microservice-db-config

volumes:
  accountsdb:
    driver: local
  paymentsdb:
    driver: local
  usersdb:
    driver: local

networks:
  finobank:
    driver: bridge