openapi: 3.0.3
info:
  title: Accounts microservice - OpenAPI 3.0
  description: Accounts microservice API Spec
  version: 1.0.0

servers:
  - url: api/v1

paths:
  /payments:
    get:
      tags:
        - Payments
      summary: Get all payments
      description: Get all payments information
      operationId: getPayments
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid request

components:
  schemas:
    ApiPayments:
      type: object
      properties:
        id:
          type: string
