openapi: 3.0.3
info:
  title: Accounts microservice - OpenAPI 3.0
  description: Accounts microservice API Spec
  version: 1.0.0

servers:
  - url: api/v1

paths: { }

components:
  schemas:
    ApiAccount:
      type: object
      properties:
        id:
          type: string
          format: uuid
        accountNumber:
          type: string
        accountName:
          type: string
        balances:
          type: array
          items:
            $ref: "#/components/schemas/ApiBalance"
        status:
          $ref: "#/components/schemas/ApiAccountStatus"
        users:
          type: array
          items:
            $ref: "#/components/schemas/ApiUser"

    ApiAccountStatus:
      enum:
        - ENABLED
        - BLOCKED
    
    ApiBalance:
      type: object
      properties:
        id:
          type: string
          format: uuid
        amount:
          type: number
        currency:
          type: string
        type:
          $ref: '#/components/schemas/ApiBalanceType'

    ApiBalanceType:
      enum:
        - AVAILABLE
        - END_OF_DAY

    ApiUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        address:
          type: string
