openapi: 3.0.3
info:
  title: Accounts microservice - OpenAPI 3.0
  description: Accounts microservice API Spec
  version: 1.0.0

servers:
  - url: api/v1

paths: { }

components:
  schemas:
    ApiAccount:
      type: object
      properties:
        id:
          type: string
          format: uuid
        accountNumber:
          type: string
        accountName:
          type: string
        balances:
          type: array
          items:
            $ref: "#/components/schemas/ApiBalance"
        status:
          $ref: "#/components/schemas/ApiAccountStatus"
        users:
          type: array
          items:
            $ref: "#/components/schemas/ApiUser"

    ApiAccountStatus:
      enum:
        - ENABLED
        - BLOCKED
    
    ApiBalance:
      type: object
      properties:
        id:
          type: string
          format: uuid
        amount:
          type: number
          minimum: 0
        creationDate:
          type: string
          format: date-time
        currency:
          type: string
        type:
          $ref: '#/components/schemas/ApiBalanceType'

    ApiBalanceEntry:
      enum:
        - CREDIT
        - DEBIT

    ApiBalanceType:
      enum:
        - AVAILABLE
        - END_OF_DAY

    ApiPayment:
      type: object
      required:
        - amount
        - currency
        - giverAccountNumber
        - beneficiaryAccountNumber
      properties:
        id:
          type: string
          format: uuid
        amount:
          type: number
          minimum: 0
        currency:
          type: string
        giverAccountNumber:
          type: string
        beneficiaryAccountNumber:
          type: string
        communication:
          type: string
        creationDate:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/ApiPaymentStatus'

    ApiPaymentStatus:
      enum:
        - EXECUTED

    ApiUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        address:
          type: string
